name: CI

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master, test]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy-3.8', 'pypy-3.9']
        exclude:
          - os: windows
            python-version: pypy3
    steps:
      - if: ${{ matrix.os == 'ubuntu' }}
        run: sudo apt-get install strace
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      - id: pip-cache-xnix
        shell: bash
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - id: pip-cache-windows
        shell: pwsh
        run: echo "dir=$(pip cache dir)" >> ${env:$GITHUB_OUTPUT}

      - uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'dev_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - run: pip install . -r dev_requirements.txt
      - run: pip freeze
      - run: pip check
      - run: doit pyflakes
      - run: doit codestyle
      - run: py.test -vv ${{ matrix.pytest-args }}
      - if: ${{ matrix.os == 'ubuntu' && matrix.python-version == '3.8' }}
        run: |
          pip install codecov
          doit coverage
          codecov
